### ISSUE TITLE
extra line - need to be deleted

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/dne-dcip-introduction-to-powershell-labs-v01#1]
CiscoDevNet/dne-dcip-introduction-to-powershell-labs-v01 
1.md file 

![](assets/images/image-01.jpg)<br/><br/>

This line will display an unnecessary small icon.

**Comment by movinalot** [comment]
I don't see the image.

**Comment by yawming** [comment]
https://learninglabs.cisco.com:8867/tracks/devnet-express-dci/devnet-express-introduction-to-powershell/dne-dcip-introduction-to-powershell-introduction-v01/step/1


[cid:image001.png@01D2D2E7.57C1C240]

**Comment by yawming** [comment]
![extra](https://cloud.githubusercontent.com/assets/4533897/26321421/9307748e-3edb-11e7-97de-57744e478b7d.png)

**Comment by movinalot** [comment]
Got it, fixed in source, will publish with any other changes
